[theme]
base = "dark"
primaryColor = "#A78BFA"
backgroundColor = "#080C18"
secondaryBackgroundColor = "#11182A"
textColor = "#F1F5F9"
font = "monospace"

[theme.sidebar]
backgroundColor = "#0B1120"
secondaryBackgroundColor = "#171F35"

[server]
headless = true
